#!/bin/bash

pushd `dirname $0` > /dev/null
BASE_DIR=`pwd`
popd > /dev/null
BASE_DIR=`dirname "$BASE_DIR"`

. "${BASE_DIR}"/conf/startup.properties

CP=.$(find "$LIB" -name '*.jar' -exec printf ":{}" \;)

export CLASSPATH=$CP

PWD="`pwd`"
cd "$BASE_DIR"

RUN_COMMAND="$JAVA ${MEM} ${OPTS} ${DEFS} pl.edu.icm.unity.server.UnityApplication ${PARAM}"
echo ${RUN_COMMAND}
if [ "${AUTHBIND}" ]
then
        "${AUTHBIND}" --deep ${RUN_COMMAND}
else
        ${RUN_COMMAND}
fi
